INSERT INTO `wd_g_accounts` VALUES ('default1', 'Default account', 'Do not delete', '2005-02-22 07:14:08', 0);

INSERT INTO `wd_g_settings` VALUES ('60316fdc', 3, 'Aff_support_click_commissions', '1', 'default1', NULL, NULL, NULL);
INSERT INTO `wd_g_settings` VALUES ('60316fd3', 3, 'Aff_support_sale_commissions', '1', 'default1', NULL, NULL, NULL);
INSERT INTO `wd_g_settings` VALUES ('60316fd4', 3, 'Aff_support_recurring_commissions', '1', 'default1', NULL, NULL, NULL);
INSERT INTO `wd_g_settings` VALUES ('60316001', 3, 'Aff_fixed_cost', '0', 'default1', NULL, NULL, NULL);
INSERT INTO `wd_g_settings` VALUES ('60316002', 3, 'Aff_join_campaign', '0', 'default1', NULL, NULL, NULL);
INSERT INTO `wd_g_settings` VALUES ('60316003', 3, 'Aff_display_news', '1', 'default1', NULL, NULL, NULL);
INSERT INTO `wd_g_settings` VALUES ('60316004', 3, 'Aff_display_resources', '0', 'default1', NULL, NULL, NULL);
INSERT INTO `wd_g_settings` VALUES ('60316005', 3, 'Aff_display_banner_stats_all', '0', 'default1', NULL, NULL, NULL);
INSERT INTO `wd_g_settings` VALUES ('60316006', 3, 'Aff_use_forced_matrix', '0', 'default1', NULL, NULL, NULL);
INSERT INTO `wd_g_settings` VALUES ('60316007', 3, 'Aff_round_numbers', '2', 'default1', NULL, NULL, NULL);
INSERT INTO `wd_g_settings` VALUES ('60316008', 3, 'Aff_currency_left_position', '0', 'default1', NULL, NULL, NULL);
INSERT INTO `wd_g_settings` VALUES ('60316009', 3, 'Aff_program_signup_bonus', '0', 'default1', NULL, NULL, NULL);
INSERT INTO `wd_g_settings` VALUES ('60316010', 3, 'Aff_program_referral_commission', '0', 'default1', NULL, NULL, NULL);
INSERT INTO `wd_g_settings` VALUES ('60316011', 3, 'Aff_overwrite_cookie', '0', 'default1', NULL, NULL, NULL);
INSERT INTO `wd_g_settings` VALUES ('60316012', 3, 'Aff_delete_cookie', '0', 'default1', NULL, NULL, NULL);
INSERT INTO `wd_g_settings` VALUES ('60316013', 3, 'Aff_referred_affiliate_allow', '0', 'default1', NULL, NULL, NULL);
INSERT INTO `wd_g_settings` VALUES ('60316014', 3, 'Aff_permanent_redirect', '0', 'default1', NULL, NULL, NULL);
INSERT INTO `wd_g_settings` VALUES ('60316015', 3, 'Aff_mail_send_type', '1', 'default1', NULL, NULL, NULL);
INSERT INTO `wd_g_settings` VALUES ('60316040', 3, 'Aff_mail_type', '1', 'default1', NULL, NULL, NULL);
INSERT INTO `wd_g_settings` VALUES ('60316041', 3, 'Aff_mail_charset', 'UTF-8', 'default1', NULL, NULL, NULL);
INSERT INTO `wd_g_settings` VALUES ('60316016', 3, 'Aff_log_level', '11', 'default1', NULL, NULL, NULL);
INSERT INTO `wd_g_settings` VALUES ('afdcffa5', 3, 'Aff_system_currency', '$', 'default1', NULL, NULL, NULL);
INSERT INTO `wd_g_settings` VALUES ('afdcffa6', 3, 'Aff_show_minihelp', '1', 'default1', NULL, NULL, NULL);
INSERT INTO `wd_g_settings` VALUES ('60316017', 3, 'Aff_default_lang', 'english', 'default1', NULL, NULL, NULL);
INSERT INTO `wd_g_settings` VALUES ('60316018', 3, 'Aff_min_payout_options', '100;200;300;400;500', 'default1', NULL, NULL, NULL);
INSERT INTO `wd_g_settings` VALUES ('60316019', 3, 'Aff_initial_min_payout', '300', 'default1', NULL, NULL, NULL);
INSERT INTO `wd_g_settings` VALUES ('60316020', 3, 'Aff_affiliateapproval', '1', 'default1', NULL, NULL, NULL);
INSERT INTO `wd_g_settings` VALUES ('60316021', 3, 'Aff_affpostsignupurl', 'postsignup.php', 'default1', NULL, NULL, NULL);
INSERT INTO `wd_g_settings` VALUES ('60316022', 3, 'Aff_allow_choose_lang', '1', 'default1', NULL, NULL, NULL);
INSERT INTO `wd_g_settings` VALUES ('60316023', 3, 'Aff_link_style', '1', 'default1', NULL, NULL, NULL);
INSERT INTO `wd_g_settings` VALUES ('60316024', 3, 'Aff_forcecommfromproductid', 'no', 'default1', NULL, NULL, NULL);
INSERT INTO `wd_g_settings` VALUES ('60316025', 3, 'Aff_maxcommissionlevels', '10', 'default1', NULL, NULL, NULL);
INSERT INTO `wd_g_settings` VALUES ('60316026', 3, 'Aff_paging', '10', 'default1', NULL, NULL, NULL);
INSERT INTO `wd_g_settings` VALUES ('60316027', 3, 'Aff_login_protection_retries', '0', 'default1', NULL, NULL, NULL);
INSERT INTO `wd_g_settings` VALUES ('60316028', 3, 'Aff_login_protection_delay', '0', 'default1', NULL, NULL, NULL);
INSERT INTO `wd_g_settings` VALUES ('60316029', 3, 'Aff_signup_username', '1', 'default1', NULL, NULL, NULL);
INSERT INTO `wd_g_settings` VALUES ('60316030', 3, 'Aff_signup_username_mandatory', 'true', 'default1', NULL, NULL, NULL);
INSERT INTO `wd_g_settings` VALUES ('60316031', 3, 'Aff_signup_name', '1', 'default1', NULL, NULL, NULL);
INSERT INTO `wd_g_settings` VALUES ('60316032', 3, 'Aff_signup_name_mandatory', 'true', 'default1', NULL, NULL, NULL);
INSERT INTO `wd_g_settings` VALUES ('60316033', 3, 'Aff_signup_surname', '1', 'default1', NULL, NULL, NULL);
INSERT INTO `wd_g_settings` VALUES ('60316034', 3, 'Aff_signup_surname_mandatory', 'true', 'default1', NULL, NULL, NULL);
INSERT INTO `wd_g_settings` VALUES ('60316035', 3, 'Aff_signup_country', '1', 'default1', NULL, NULL, NULL);
INSERT INTO `wd_g_settings` VALUES ('60316036', 3, 'Aff_signup_country_mandatory', 'true', 'default1', NULL, NULL, NULL);
INSERT INTO `wd_g_settings` VALUES ('60316037', 1, 'Glob_accounts_dir', 'accounts', 'default1', NULL, NULL, NULL);
INSERT INTO `wd_g_settings` VALUES ('60316038', 3, 'Glob_acct_custom_template', '1', 'default1', NULL, NULL, NULL);
INSERT INTO `wd_g_settings` VALUES ('23423423', 3, 'Aff_email_dailyreport', '1', 'default1', NULL, NULL, NULL);

INSERT INTO wd_g_emailtemplates VALUES("1", "AFF_EMAIL_SIGNUP", "Thank you for joining", "Dear $Affiliate_name,\r\n\r\nthank you for joining our affiliate program.\r\n\r\nYour username is: $Affiliate_username\r\nYour password is: $Affiliate_password\r\nYou can log in into your control panel in url: http://www.webradev.com/affiliate/affiliates/\r\n\r\nIf you have any requests regarding the affiliate program, don\'t hesitate to contact me on the email address info@webradev.com.\r\n\r\nsincerelly,\r\n\r\nMaros Fric\r\nhttp://www.webradev.com", "0", "English", "default1");
INSERT INTO wd_g_emailtemplates VALUES("2", "AFF_EMAIL_NTF_SIGNUP", "New affiliate signup", "POST Affiliate Pro Email notification\r\n\r\nNew affiliate joined the affiliate program. Affiliate details:\r\n\r\nName: $Affiliate_name\r\nUsername/email: $Affiliate_username\r\nWebsite: $Affiliate_website\r\nCountry: $Affiliate_country\r\nStatus: $Affiliate_status ", "0", "English", "default1");
INSERT INTO wd_g_emailtemplates VALUES("3", "AFF_EMAIL_NTF_SALE", "New sale", "POST Affiliate Pro Email notification\r\n\r\nNew sale was registered by affiliate program. Sale details:\r\n\r\nTransaction ID:  $Sale_id\r\nCommission:  $Sale_commission\r\nTotal cost:  $Sale_totalcost\r\nOrderID:  $Sale_orderid\r\nProductID:  $Sale_productid\r\nDate&time:  $Sale_date\r\nAffiliate:  $Sale_affiliate\r\nStatus:  $Sale_status\r\nIP address:  $Sale_ip\r\nReferrer:  $Sale_referrer\r\n", "0", "English", "default1");
INSERT INTO wd_g_emailtemplates VALUES("4", "AFF_EMAIL_DAILY_REP", "Daily report for $Date", "Daily report for $Date\r\n\r\nImpressions:  $Impressions\r\n\r\nClicks:  $Clicks\r\n\r\nSales\r\n-----------------------------------\r\nApproved:  $Sales_approved\r\n2nd tier approved: $Sales_approved_2ndtier\r\n\r\nWaiting for approval: $Sales_waitingapproval\r\n2nd tier waiting for approval: $Sales_waitingapproval_2ndtier\r\n\r\nDeclined:  $Sales_declined\r\n2nd tier declined:  $Sales_declined_2ndtier\r\n\r\n\r\nCommissions\r\n-----------------------------------\r\nApproved:  $Commissions_approved\r\n2nd tier approved: $Commissions_approved_2ndtier\r\n\r\nWaiting for approval: $Commissions_waitingapproval\r\n2nd tier waiting for approval: $Commissions_waitingapproval_2ndtier\r\n-----------------------------------\r\n\r\nDeclined:  $Commissions_declined\r\n2nd tier declined:  $Commissions_declined_2ndtier\r\n\r\n", "0", "English", "default1");
INSERT INTO wd_g_emailtemplates VALUES("8", "AFF_EMAIL_MONTH_REP", "Merchant Monthly Report", "Monthly report for $Month\r\n\r\nImpressions:  $Impressions\r\n\r\nClicks:  $Clicks\r\n\r\nSales\r\n-----------------------------------\r\nApproved:  $Sales_approved\r\n2nd tier approved: $Sales_approved_2ndtier\r\n\r\nWaiting for approval: $Sales_waitingapproval\r\n2nd tier waiting for approval: $Sales_waitingapproval_2ndtier\r\n\r\nDeclined:  $Sales_declined\r\n2nd tier declined:  $Sales_declined_2ndtier\r\n\r\n\r\nCommissions\r\n-----------------------------------\r\nApproved:  $Commissions_approved\r\n2nd tier approved: $Commissions_approved_2ndtier\r\n\r\nWaiting for approval: $Commissions_waitingapproval\r\n2nd tier waiting for approval: $Commissions_waitingapproval_2ndtier\r\n-----------------------------------\r\n\r\nDeclined:  $Commissions_declined\r\n2nd tier declined:  $Commissions_declined_2ndtier\r\n\r\nTransactions\r\n-----------------------------------\r\nSales list:\r\n$Sales_list\r\n\r\nLeads list:\r\n$Leads_list\r\n", "0", "English", "default1");
INSERT INTO wd_g_emailtemplates VALUES("5", "AFF_EMAIL_AF_NTF_SGN", "New affiliate signup", "POST Affiliate Pro Email notification\r\n\r\nNew affiliate joined the affiliate program. Affiliate details:\r\n\r\nUsername/email: $Affiliate_username\r\nWebsite: $Affiliate_website\r\nCountry: $Affiliate_country\r\nStatus: $Affiliate_status ", "0", "English", "default1");
INSERT INTO wd_g_emailtemplates VALUES("6", "AFF_EMAIL_AF_NTF_SLE", "New sale commission", "POST Affiliate Pro Email notification\r\n\r\nNew sale was registered by affiliate program. Sale details:\r\n\r\nCommission:  $Sale_commission\r\nOrderID:  $Sale_orderid\r\nProductID:  $Sale_productid\r\nDate&time:  $Sale_date\r\nStatus:  $Sale_status\r\nIP address:  $Sale_ip\r\nReferrer:  $Sale_referrer\r\n", "0", "English", "default1");
INSERT INTO wd_g_emailtemplates VALUES("7", "AFF_EMAIL_AF_DL_REP", "Daily report", "Daily report for $Date\r\n\r\nImpressions:  $Impressions\r\n\r\nClicks:  $Clicks\r\n\r\nSales\r\n-----------------------------------\r\nApproved:  $Sales_approved\r\n2nd tier approved: $Sales_approved_2ndtier\r\n\r\nWaiting for approval: $Sales_waitingapproval\r\n2nd tier waiting for approval: $Sales_waitingapproval_2ndtier\r\n\r\nDeclined:  $Sales_declined\r\n2nd tier declined:  $Sales_declined_2ndtier\r\n\r\n\r\nCommissions\r\n-----------------------------------\r\nApproved:  $Commissions_approved\r\n2nd tier approved: $Commissions_approved_2ndtier\r\n\r\nWaiting for approval: $Commissions_waitingapproval\r\n2nd tier waiting for approval: $Commissions_waitingapproval_2ndtier\r\n-----------------------------------\r\n\r\nDeclined:  $Commissions_declined\r\n2nd tier declined:  $Commissions_declined_2ndtier\r\n", "0", "English", "default1");
INSERT INTO wd_g_emailtemplates VALUES("9", "AFF_EMAIL_AF_ML_REP", "Monthly report", "Monthly report for $Month\r\n\r\nImpressions:  $Impressions\r\n\r\nClicks:  $Clicks\r\n\r\nSales\r\n-----------------------------------\r\nApproved:  $Sales_approved\r\n2nd tier approved: $Sales_approved_2ndtier\r\n\r\nWaiting for approval: $Sales_waitingapproval\r\n2nd tier waiting for approval: $Sales_waitingapproval_2ndtier\r\n\r\nDeclined:  $Sales_declined\r\n2nd tier declined:  $Sales_declined_2ndtier\r\n\r\n\r\nCommissions\r\n-----------------------------------\r\nApproved:  $Commissions_approved\r\n2nd tier approved: $Commissions_approved_2ndtier\r\n\r\nWaiting for approval: $Commissions_waitingapproval\r\n2nd tier waiting for approval: $Commissions_waitingapproval_2ndtier\r\n-----------------------------------\r\n\r\nDeclined:  $Commissions_declined\r\n2nd tier declined:  $Commissions_declined_2ndtier\r\n\r\nTransactions\r\n-----------------------------------\r\nSales list:\r\n$Sales_list\r\n\r\nLeads list:\r\n$Leads_list\r\n", "0", "English", "default1");
INSERT INTO wd_g_emailtemplates VALUES("491603db", "AFF_EMAIL_FORGOTPAS1", "Forgot password - step1", "Hello,\r\n\r\nplease use the verification code below in the step 2:\r\n$Affiliate_verification_code\r\n\r\n\r\n", "0", "english", "default1");
INSERT INTO wd_g_emailtemplates VALUES("a8a1013a", "AFF_EMAIL_FORGOTPAS2", "Forgot password", "Hello,\r\n\r\nyour password was set to: $Affiliate_password\r\nYour username is: $Affiliate_username", "0", "english", "default1");
INSERT INTO wd_g_emailtemplates VALUES("1916de1b", "AFF_EMAIL_CONTACT_US", "Message from affiliate", "$Date $Time\r\n\r\nAffiliate: $Affiliate_id - $Affiliate_name\r\n\r\nSubject: $Affiliate_emailsubject\r\n\r\nText:\r\n$Affiliate_emailtext", "0", "english", "default1");

INSERT INTO wd_g_righttypes VALUES("02", NULL, "", "campaigns", "aff_camp_product_categories", "modify", "0000-00-00 00:00:00", "L_G_RT_CAMPAIGNS", "L_G_CAMPAIGNS", "L_G_RT_MODIFY", "2");
INSERT INTO wd_g_righttypes VALUES("01", "02", "", "campaigns", "aff_camp_product_categories", "view", "0000-00-00 00:00:00", "L_G_RT_CAMPAIGNS", "L_G_CAMPAIGNS", "L_G_RT_VIEW", "1");
INSERT INTO wd_g_righttypes VALUES("03", "04", "", "affiliates", "aff_aff_affiliates", "view", "0000-00-00 00:00:00", "L_G_AFFILIATES", "L_G_AFFILIATES", "L_G_RT_VIEW", "1");
INSERT INTO wd_g_righttypes VALUES("05", "06", "", "affiliates", "aff_aff_pay_affiliates", "view", "0000-00-00 00:00:00", "L_G_AFFILIATES", "L_G_PAYOUT", "L_G_RT_VIEW", "1");
INSERT INTO wd_g_righttypes VALUES("07", "08", "", "affiliates", "aff_aff_accounting", "view", "0000-00-00 00:00:00", "L_G_AFFILIATES", "L_G_ACCOUNTING", "L_G_RT_VIEW", "1");
INSERT INTO wd_g_righttypes VALUES("09", "10", "", "transactions", "aff_trans_transactions", "view", "0000-00-00 00:00:00", "L_G_TRANSACTIONS", "L_G_TRANSACTIONS", "L_G_RT_VIEW", "1");
INSERT INTO wd_g_righttypes VALUES("12", NULL, "", "reports", "aff_rep_quick_report", "view", "0000-00-00 00:00:00", "L_G_REPORTS", "L_G_QUICK", "L_G_RT_VIEW", "0");
INSERT INTO wd_g_righttypes VALUES("13", NULL, "", "reports", "aff_rep_transactions", "view", "0000-00-00 00:00:00", "L_G_REPORTS", "L_G_TRANSACTIONS", "L_G_RT_VIEW", "0");
INSERT INTO wd_g_righttypes VALUES("14", NULL, "", "reports", "aff_rep_traffic_and_sales", "view", "0000-00-00 00:00:00", "L_G_REPORTS", "L_G_TRAFFIC", "L_G_RT_VIEW", "0");
INSERT INTO wd_g_righttypes VALUES("15", NULL, "", "reports", "aff_rep_top_20_affiliates", "view", "0000-00-00 00:00:00", "L_G_REPORTS", "L_G_TOP20AFFILIATES", "L_G_RT_VIEW", "0");
INSERT INTO wd_g_righttypes VALUES("39", NULL, "", "reports", "aff_rep_top_campaigns", "view", "0000-00-00 00:00:00", "L_G_REPORTS", "L_G_TOPCAMPAIGNS", "L_G_RT_VIEW", "0");
INSERT INTO wd_g_righttypes VALUES("16", NULL, "", "reports", "aff_rep_number_of_affiliates", "view", "0000-00-00 00:00:00", "L_G_REPORTS", "L_G_AFFILIATECOUNTS", "L_G_RT_VIEW", "0");
INSERT INTO wd_g_righttypes VALUES("38", NULL, "", "reports", "aff_rep_top_urls", "view", "0000-00-00 00:00:00", "L_G_REPORTS", "L_G_TOPREFERRINGURLS", "L_G_RT_VIEW", "0");
INSERT INTO wd_g_righttypes VALUES("17", "18", "", "communication", "aff_comm_email_templates", "view", "0000-00-00 00:00:00", "L_G_COMMUNICATION", "L_G_EMAILTEMPLATES", "L_G_RT_VIEW", "1");
INSERT INTO wd_g_righttypes VALUES("19", NULL, "", "communication", "aff_comm_broadcast_email", "use", "0000-00-00 00:00:00", "L_G_COMMUNICATION", "L_G_BROADCAST_MESSAGE", "L_G_RT_USE", "0");
INSERT INTO wd_g_righttypes VALUES("20", "21", "", "tools", "aff_tool_admins", "view", "0000-00-00 00:00:00", "L_G_TOOLS", "L_G_ADMINS", "L_G_RT_VIEW", "1");
INSERT INTO wd_g_righttypes VALUES("22", "23", "", "tools", "aff_tool_user_profiles", "view", "0000-00-00 00:00:00", "L_G_TOOLS", "L_G_USER_PROFILES_MANAGER", "L_G_RT_VIEW", "1");
INSERT INTO wd_g_righttypes VALUES("24", "25", "", "tools", "aff_tool_settings", "view", "0000-00-00 00:00:00", "L_G_TOOLS", "L_G_SETTINGS", "L_G_RT_VIEW", "1");
INSERT INTO wd_g_righttypes VALUES("26", NULL, "", "tools", "aff_tool_integration", "view", "0000-00-00 00:00:00", "L_G_TOOLS", "L_G_INTEGRATIONCODE", "L_G_RT_VIEW", "0");
INSERT INTO wd_g_righttypes VALUES("27", "28", "", "tools", "aff_tool_history", "view", "0000-00-00 00:00:00", "L_G_TOOLS", "L_G_HISTORY", "L_G_RT_VIEW", "1");
INSERT INTO wd_g_righttypes VALUES("29", NULL, "", "tools", "aff_tool_db_maintenance", "backup", "0000-00-00 00:00:00", "L_G_TOOLS", "L_G_MAINTENANCE", "L_G_RT_BACKUP", "1");
INSERT INTO wd_g_righttypes VALUES("04", NULL, "", "affiliates", "aff_aff_affiliates", "modify", "0000-00-00 00:00:00", "L_G_AFFILIATES", "L_G_AFFILIATES", "L_G_RT_MODIFY", "2");
INSERT INTO wd_g_righttypes VALUES("06", NULL, "", "affiliates", "aff_aff_pay_affiliates", "modify", "0000-00-00 00:00:00", "L_G_AFFILIATES", "L_G_PAYOUT", "L_G_RT_MODIFY", "2");
INSERT INTO wd_g_righttypes VALUES("08", NULL, "", "affiliates", "aff_aff_accounting", "modify", "0000-00-00 00:00:00", "L_G_AFFILIATES", "L_G_ACCOUNTING", "L_G_RT_MODIFY", "2");
INSERT INTO wd_g_righttypes VALUES("10", "11", "", "transactions", "aff_trans_transactions", "approvedecline", "0000-00-00 00:00:00", "L_G_TRANSACTIONS", "L_G_TRANSACTIONS", "L_G_RT_APPROVE_DECLINE", "2");
INSERT INTO wd_g_righttypes VALUES("11", NULL, "", "transactions", "aff_trans_transactions", "modify", "0000-00-00 00:00:00", "L_G_TRANSACTIONS", "L_G_TRANSACTIONS", "L_G_RT_MODIFY", "3");
INSERT INTO wd_g_righttypes VALUES("18", NULL, "", "communication", "aff_comm_email_templates", "modify", "0000-00-00 00:00:00", "L_G_COMMUNICATION", "L_G_EMAILTEMPLATES", "L_G_RT_MODIFY", "2");
INSERT INTO wd_g_righttypes VALUES("21", NULL, "", "tools", "aff_tool_admins", "modify", "0000-00-00 00:00:00", "L_G_TOOLS", "L_G_ADMINS", "L_G_RT_MODIFY", "2");
INSERT INTO wd_g_righttypes VALUES("23", NULL, "", "tools", "aff_tool_user_profiles", "modify", "0000-00-00 00:00:00", "L_G_TOOLS", "L_G_USER_PROFILES_MANAGER", "L_G_RT_MODIFY", "2");
INSERT INTO wd_g_righttypes VALUES("25", NULL, "", "tools", "aff_tool_settings", "modify", "0000-00-00 00:00:00", "L_G_TOOLS", "L_G_SETTINGS", "L_G_RT_MODIFY", "2");
INSERT INTO wd_g_righttypes VALUES("28", NULL, "", "tools", "aff_tool_history", "purge", "0000-00-00 00:00:00", "L_G_TOOLS", "L_G_HISTORY", "L_G_RT_PURGE", "2");
INSERT INTO wd_g_righttypes VALUES("30", NULL, "", "tools", "aff_tool_db_maintenance", "restore", "0000-00-00 00:00:00", "L_G_TOOLS", "L_G_MAINTENANCE", "L_G_RT_RESTORE", "2");
INSERT INTO wd_g_righttypes VALUES("31", "32", "", "transactions", "aff_trans_recurr_transactions", "view", "0000-00-00 00:00:00", "L_G_TRANSACTIONS", "L_G_RECURRINGCOMMS", "L_G_RT_VIEW", "1");
INSERT INTO wd_g_righttypes VALUES("32", "33", "", "transactions", "aff_trans_recurr_transactions", "approvedecline", "0000-00-00 00:00:00", "L_G_TRANSACTIONS", "L_G_RECURRINGCOMMS", "L_G_RT_APPROVE_DECLINE", "2");
INSERT INTO wd_g_righttypes VALUES("33", NULL, "", "transactions", "aff_trans_recurr_transactions", "modify", "0000-00-00 00:00:00", "L_G_TRANSACTIONS", "L_G_RECURRINGCOMMS", "L_G_RT_MODIFY", "3");
INSERT INTO wd_g_righttypes VALUES("35", NULL, "", "campaigns", "aff_camp_banner_links", "modify", "0000-00-00 00:00:00", "L_G_RT_CAMPAIGNS", "L_G_BANNERS", "L_G_RT_MODIFY", "2");
INSERT INTO wd_g_righttypes VALUES("34", "35", "", "campaigns", "aff_camp_banner_links", "view", "0000-00-00 00:00:00", "L_G_RT_CAMPAIGNS", "L_G_BANNERS", "L_G_RT_VIEW", "1");
INSERT INTO wd_g_righttypes VALUES("36", "37", "", "communication", "aff_comm_communications", "view", "0000-00-00 00:00:00", "L_G_COMMUNICATION", "L_G_COMMUNICATION", "L_G_RT_VIEW", "1");
INSERT INTO wd_g_righttypes VALUES("37", NULL, "", "communication", "aff_comm_communications", "modify", "0000-00-00 00:00:00", "L_G_COMMUNICATION", "L_G_COMMUNICATION", "L_G_RT_MODIFY", "2");
INSERT INTO wd_g_righttypes VALUES("repsubid", NULL, "", "reports", "aff_rep_subid", "view", "0000-00-00 00:00:00", "L_G_REPORTS", "L_G_SUBIDREPORTS", "L_G_RT_VIEW", "0");
INSERT INTO wd_g_righttypes VALUES("f2ghf23h", NULL, "", "communication", "aff_comm_history", "view", "0000-00-00 00:00:00", "L_G_COMMHISTORY", "L_G_COMMHISTORY", "L_G_RT_VIEW", "1");
INSERT INTO wd_g_righttypes VALUES("5g6jg4jh", NULL, "", "tools", "aff_tool_template", "modify", "0000-00-00 00:00:00", "L_G_TOOLS", "L_G_TEMPLATEEDITOR", "L_G_RT_MODIFY", "2");
INSERT INTO wd_g_righttypes VALUES("7g5jhghj", NULL, "", "tools", "aff_tool_resource", "modify", "0000-00-00 00:00:00", "L_G_TOOLS", "L_G_AFFRESOURCES", "L_G_RT_MODIFY", "2");
INSERT INTO wd_g_righttypes VALUES("repgeost", NULL, "", "reports", "aff_rep_geo_stats", "view", "0000-00-00 00:00:00", "L_G_REPORTS", "L_G_GEOSTATSREPORTS", "L_G_RT_VIEW", "0");
INSERT INTO wd_g_righttypes VALUES("1a5s8s4a", NULL, "", "tools", "aff_tool_signupsettings", "view", "0000-00-00 00:00:00", "L_G_TOOLS", "L_G_AFFSIGNUPSETTINGS", "L_G_RT_VIEW", "0");
INSERT INTO wd_g_righttypes VALUES("41", NULL, "", "reports", "aff_rep_non_perform_affiliates", "view", "0000-00-00 00:00:00", "L_G_REPORTS", "L_G_NONPERFORMAFFILIATES", "L_G_RT_VIEW", "0");
INSERT INTO wd_g_righttypes VALUES("s4a8ju8n", NULL, "", "tools", "aff_tool_affloginsettings", "view", "0000-00-00 00:00:00", "L_G_TOOLS", "L_G_LOGINSCREENSETTINGS", "L_G_RT_VIEW", "0");
INSERT INTO wd_g_righttypes VALUES("da89dasn", NULL, "", "tools", "aff_tool_afflayoutsettings", "view", "0000-00-00 00:00:00", "L_G_TOOLS", "L_G_LAYOUTSETTINGS", "L_G_RT_VIEW", "0");
INSERT INTO wd_g_righttypes VALUES("4gjg4jg6", NULL, "", "reports", "aff_rep_non_perform_affiliates", "view", "0000-00-00 00:00:00", "L_G_REPORTS", "L_G_NONPERFOMAFFILIATES", "L_G_RT_VIEW", "0");

INSERT INTO `wd_g_userprofiles` VALUES ('userpro1', 'Default admin profile', '3', 'default1');

INSERT INTO wd_g_userrights VALUES("303322f3", "userpro1", "01");
INSERT INTO wd_g_userrights VALUES("98edf3f2", "userpro1", "02");
INSERT INTO wd_g_userrights VALUES("6d0469b2", "userpro1", "03");
INSERT INTO wd_g_userrights VALUES("8a264905", "userpro1", "04");
INSERT INTO wd_g_userrights VALUES("3591ac15", "userpro1", "05");
INSERT INTO wd_g_userrights VALUES("fe7c978a", "userpro1", "06");
INSERT INTO wd_g_userrights VALUES("9eaa424f", "userpro1", "07");
INSERT INTO wd_g_userrights VALUES("de631656", "userpro1", "08");
INSERT INTO wd_g_userrights VALUES("62670421", "userpro1", "09");
INSERT INTO wd_g_userrights VALUES("8a721021", "userpro1", "10");
INSERT INTO wd_g_userrights VALUES("6bfdc423", "userpro1", "11");
INSERT INTO wd_g_userrights VALUES("55bae64f", "userpro1", "12");
INSERT INTO wd_g_userrights VALUES("0acf1810", "userpro1", "13");
INSERT INTO wd_g_userrights VALUES("7a209eb2", "userpro1", "14");
INSERT INTO wd_g_userrights VALUES("75d8c0f7", "userpro1", "15");
INSERT INTO wd_g_userrights VALUES("c2c671fe", "userpro1", "16");
INSERT INTO wd_g_userrights VALUES("0f2295a4", "userpro1", "17");
INSERT INTO wd_g_userrights VALUES("f5f6a7f6", "userpro1", "18");
INSERT INTO wd_g_userrights VALUES("e4025111", "userpro1", "19");
INSERT INTO wd_g_userrights VALUES("d6f68d7a", "userpro1", "20");
INSERT INTO wd_g_userrights VALUES("c677b9d0", "userpro1", "21");
INSERT INTO wd_g_userrights VALUES("39d51858", "userpro1", "22");
INSERT INTO wd_g_userrights VALUES("df484242", "userpro1", "23");
INSERT INTO wd_g_userrights VALUES("18f2a81a", "userpro1", "24");
INSERT INTO wd_g_userrights VALUES("c702dc78", "userpro1", "25");
INSERT INTO wd_g_userrights VALUES("46cb70c0", "userpro1", "26");
INSERT INTO wd_g_userrights VALUES("fd95d2e5", "userpro1", "27");
INSERT INTO wd_g_userrights VALUES("44d46fef", "userpro1", "28");
INSERT INTO wd_g_userrights VALUES("0723cf68", "userpro1", "29");
INSERT INTO wd_g_userrights VALUES("0e8581e8", "userpro1", "30");
INSERT INTO wd_g_userrights VALUES("a0c939d5", "userpro1", "31");
INSERT INTO wd_g_userrights VALUES("c5bcad90", "userpro1", "32");
INSERT INTO wd_g_userrights VALUES("715114df", "userpro1", "33");
INSERT INTO wd_g_userrights VALUES("e5597917", "userpro1", "34");
INSERT INTO wd_g_userrights VALUES("79cc1788", "userpro1", "35");
INSERT INTO wd_g_userrights VALUES("eede7703", "userpro1", "36");
INSERT INTO wd_g_userrights VALUES("cdc30ab1", "userpro1", "37");
INSERT INTO wd_g_userrights VALUES("cdc59g1u", "userpro1", "38");
INSERT INTO wd_g_userrights VALUES("c285fdsg", "userpro1", "39");
INSERT INTO wd_g_userrights VALUES("hgj4g5jh", "userpro1", "f2ghf23h");
INSERT INTO wd_g_userrights VALUES("jhg4g4jh", "userpro1", "5g6jg4jh");
INSERT INTO wd_g_userrights VALUES("56ghjg4j", "userpro1", "7g5jhghj");
INSERT INTO wd_g_userrights VALUES("5894jg4g", "userpro1", "1a5s8s4a");
INSERT INTO wd_g_userrights VALUES("g45h4gh8", "userpro1", "41");
INSERT INTO wd_g_userrights VALUES("5894jg4g", "userpro1", "s4a8ju8n");
INSERT INTO wd_g_userrights VALUES("89fdas9a", "userpro1", "da89dasn");
INSERT INTO wd_g_userrights VALUES("89fdas9b", "userpro1", "4gjg4jg6");

INSERT INTO `wd_g_users` VALUES ('2', 'default1', '', 'test@test.test', 'test', 'Test', 'Surname', 2, '', '2005-02-22 07:08:33', NULL, 0, '', 4, '', 0, 0, '','','','','','','','','','','','','','','','','', 0);

INSERT INTO `wd_pa_campaigns` VALUES ('1', 'default1', 'Test Sale campaign', 'Test Sale campaign description', 'Test Sale campaign short description','2005-02-22 10:28:23', 0, 0, 4, '123;456;789');

INSERT INTO `wd_pa_banners` VALUES ('2', 'Test banner', 'http://www.qualityunit.com/', NULL, 1, 0, '1');

INSERT INTO `wd_pa_campaigncategories` VALUES ('1', 'L_G_UNASSIGNED_USERS', 0, 10, 0, 20, 15, '$', NULL, 1, '1', '$', '$', 0, 9, 0, 8, 0, 7, 0, 6, 0, 5, 0, 4, 0, 3, 0, 2, 0, 1, '$', 9, 8, 7, 6, 5, 4, 3, 2, 1);

INSERT INTO wd_pa_payoutoptions VALUES("paypal01", "default1", "PayPal", "0", "PPEMAIL\\t$Affiliate_amount\\tUSD\\t$Affiliate_name\\r\\n", "0", "L_G_METHODPAYPAL", "2", "<form action=\"https://www.paypal.com/cgi-bin/webscr\" method=\"post\" target=_blank>\r\n<input type=\"hidden\" name=\"currency_code\" value=\"USD\">\r\n<input type=\"hidden\" name=\"no_note\" value=\"1\">\r\n<input type=\"hidden\" name=\"amount\" value=\"$Affiliate_amount\">\r\n<input type=\"hidden\" name=\"item_number\" value=\"Affiliate_Payment_$Date\">\r\n<input type=\"hidden\" name=\"item_name\" value=\"Affiliate Program Payment\">\r\n<input type=\"hidden\" name=\"business\" value=\"$Affiliate_username\">\r\n<input type=\"hidden\" name=\"cmd\" value=\"_xclick\">\r\n<input type=\"submit\" name=\"submit\" value=\"Pay by PayPal\">\r\n</form>\r\n");
INSERT INTO wd_pa_payoutoptions VALUES ('moneyboo','default1','MoneyBookers',0,'',0,'L_G_PAYOUTMB', 3, '');
INSERT INTO wd_pa_payoutoptions VALUES ('check001','default1','Check',0,'',0,'L_G_PAYOUTCHECK', 1, '');
INSERT INTO wd_pa_payoutoptions VALUES ('wiretran','default1','Bank/Wire transfer',0,'',0,'L_G_PAYOUTWIRE', 4, '');


INSERT INTO wd_pa_payoutfields VALUES ('paypal01','paypal01','PPEMAIL','PayPal Email','L_G_METHODFIELDPAYPALEMAIL',1,0,1,'',1,'');
INSERT INTO wd_pa_payoutfields VALUES ('moneybo1','moneyboo','MBEMAIL','MoneyBookers email','L_G_PAYOUTFIELDMBEMAIL',1,0,1,'',1,'');
INSERT INTO wd_pa_payoutfields VALUES ('check001','check001','CHPAYABLETO','Payable to','L_G_PAYOUTFIELDPAYABLETO',1,0,1,'',1,'');
INSERT INTO wd_pa_payoutfields VALUES ('wiretra1','wiretran','BANKACCNAME','Bank account name','L_G_PAYOUTFIELDBANKACCNAME',1,0,1,'',1,'');
INSERT INTO wd_pa_payoutfields VALUES ('wiretra2','wiretran','BANKNAME','Bank name','L_G_PAYOUTFIELDBANKNAME',1,0,1,'',2,'');
INSERT INTO wd_pa_payoutfields VALUES ('wiretra3','wiretran','BANKACCNUMBER','Account number','L_G_PAYOUTFIELDACCNUMBER',1,0,1,'',3,'');
INSERT INTO wd_pa_payoutfields VALUES ('wiretra4','wiretran','BANKCODE','Bank code','L_G_PAYOUTFIELDBANKCODE',1,0,1,'',4,'');
INSERT INTO wd_pa_payoutfields VALUES ('wiretra5','wiretran','BANKADDRESS','Bank address','L_G_PAYOUTFIELDBANKADDRESS',1,0,1,'',5,'');
INSERT INTO wd_pa_payoutfields VALUES ('wiretra6','wiretran','BANKSWIFT','S.W.I.F.T code','L_G_PAYOUTFIELDSWIFT',1,0,1,'',6,'');



