<?php 
    include("settings/globalConst.php");
?>
<html>
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<title>PAP Tests</title>
<link href="style.css" type="text/css" rel="stylesheet">
<SCRIPT language=JavaScript src="../include/QUnit/functions.js"></SCRIPT>
<script>
// function for checking or unchecking all items
var checkedAllItems = false;

// preload images
//...
</script>
</head>

<body topmargin="0" leftmargin="0" marginwidth="0" marginheight="0"  bgcolor="#FFFFFF" text="#000000" link="#000000" vlink="#000000" alink="#000000">
<table width="100%" height="100%" border="0" cellspacing="0" cellpadding="0">
<tr>
  <td colspan="2">
  <!--Start header-->
  <table width="100%" border="0" cellspacing="0" cellpadding="0">
<tr>
    <td class="headerLogo"><img src="./templates/affiliate/default/images/web_logo.gif" class="logo333" border="0"></td>

    <td class="headerLogo" nowrap>
    </td>
    <td class="topUserInfo" align="right" valign="top">
    </td>
</tr>
<tr>
  <td class="topMenuLine" colspan="3"></td>
</tr>
<tr>
  <td class="topMenuLineAboveContent" colspan="3"><img src="./templates/affiliate/default/images/blank.gif" width="1" height="1" border="0"></td>
</tr>
</table>
  <!--End header-->
  </td>
</tr>
<tr height="100%">
  <td class="contents">
  <table width="100%" height="100%" border="0" cellspacing="0" cellpadding="3">
  <tr>
    <td valign="top" align="center">
    <br>
    <!--Begin content-->
    
    <table class=listing width="500" border=0 cellspacing=0 cellpadding=2>
    <tr><td class=tableheader colspan=""><img src="./templates/affiliate/default/images/farrow.png" border="10">&nbsp;<b>Tests</b></td></tr><tr>
    <tr><td>&nbsp;</td></tr>
    <tr>
        <td valign=top align=center>
        <p>
            <a href="./merchants/"><b>Merchants Control Panel</b></a><br><br>
            <a href="./affiliates/"><b>Affiliates Control Panel</b></a><br><br>
            <a href="./affsignup.php"><b>Affiliate Signup page (clean)</b></a><br><br>
            <a href="./affsignup_sample.php"><b>Affiliate Signup page (sample)</b></a><br><br>
            <a href="./scripts/signup.php"><b>Affiliate Signup page (autogenerated)</b></a><br><br>
            <a href="./click_test.htm"><b>Click test page</b></a><br><br>
            <a href="./sale_test.htm"><b>Sale test page</b></a><br><br>
        </p>
        </td>
    </tr>
    </tr>
    </table>
    
    <br><br>
    
    <table class=listing width="500" border=0 cellspacing=0 cellpadding=2>
    <tr><td class=tableheader colspan=""><img src="./templates/affiliate/default/images/farrow.png" border="10">&nbsp;<b>Documentation</b></td></tr><tr>
    <tr><td>&nbsp;</td></tr>
    <tr>
        <td valign=top align=center>
        <p>
            <a href="http://www.qualityunit.com/help/index.php?pcid=_&psid=c5fd44d260" target=_blank><b>Readme guide (post installation steps)</b></a><br><br>
            <a href="http://www.qualityunit.com/help/index.php?pcid=_&psid=3cca5001be" target=_blank><b>Integration with shopping carts/payment gateways</b></a><br><br>
            <a href="http://www.qualityunit.com/help/index.php?pcid=_&psid=25a9d5cb99" target=_blank><b>Frequently asked questions</b></a><br><br>
            <a href="http://www.qualityunit.com/help/index.php?pcid=_&psid=9c94e0d133" target=_blank><b>Installation & upgrade guide</b></a><br><br>
        </p>
        </td>
    </tr>
    </tr>
    </table>
    <!--end content--> 
    </td>
  </tr>
  </table>
  </td>
</tr>

<tr>
  <td colspan="3">
  <!--Begin footer-->
  <table width="100%" border="0" cellspacing="0" cellpadding="2">
<tr>
    <td class="footer" align="left" valign="middle" width="33%">
      <div class="poweredby"><a target=_blank href="http://www.qualityunit.com/postaffiliatepro/">Affiliate software</a> by QualityUnit</div>
    </td>
    <td class="footer" align="center" valign="middle" width="33%">
        version <?php echo POSTGLOBAL_VERSION?>    </td>
    <td class="footer" align="right" valign="middle" width="33%">
               &nbsp;   
    </td>    
</tr>
</table>
  <!--End footer-->
  </td>
</tr>
</table>

</body> 
</html>
