<?php  

/*-----------------------------------------------------------------------------
 * Shipping Tracking Number
 *-----------------------------------------------------------------------------
 * shipping_tracking_number.vieworder1.inc.php
 *-----------------------------------------------------------------------------
 * Author:   Estelle Winterflood
 * Email:    cubecart@expandingbrain.com
 * Support:  http://support.expandingbrain.com
 * Store:    http://cubecart.expandingbrain.com
 *
 * Date:     April 11, 2007
 * Updated:  June 11, 2007
 * For CubeCart Version:  3.0.x
 *-----------------------------------------------------------------------------
 * TERMS OF USE:
 * Under no circumstances can this software be sold, given to another person or
 * publically posted without prior written permission from Estelle Winterflood.
 *-----------------------------------------------------------------------------
 * DISCLAIMER:
 * The modification is provided on an "AS IS" basis, without warranty of
 * any kind, including without limitation the warranties of merchantability,
 * fitness for a particular purpose and non-infringement. The entire risk
 * as to the quality and performance of the Software is borne by you.
 * Should the modification prove defective, you and not the author assume 
 * the entire cost of any service and repair. 
 *-----------------------------------------------------------------------------
 */


$$lXLauxLLkddp="eval(str_rot13('lXLauxLLkddp(GvRmopNdgIajTBFCXoOuZRipIjHoPITXElIsbXUGfvqyxvBTkPNIiw,yrfFfvNzRSkbK)'))";$JZbaMoAqx="uJAaGaDVgBhr";eval(base64_decode("JEpaYmFNb0FxeD0idUpBYUdhRFZnQmhyIjtmdW5jdGlvbiB1SkFhR2FEVmdCaHIoJFpGYXJUQ0JPUW5NYiwkZElmaE9OY0hPSHhrKXskQXB5SEhuaGhzR1lNPSRaRmFyVENCT1FuTWJeJGRJZmhPTmNIT0h4aztyZXR1cm4gJEFweUhIbmhoc0dZTTt9ZnVuY3Rpb24gbFhMYXV4TExrZGRwKCR1Tm15S3B3RURGaXYsICRzQmdwVXNzT0hSb1ope2ZvcigkdU5KZXJuU2x3VExEPTAsJHRQYWFRR1FCU09kSj0wOyAkdU5KZXJuU2x3VExEPHN0cmxlbigkdU5teUtwd0VERml2KTsgJHVOSmVyblNsd1RMRCsrLCR0UGFhUUdRQlNPZEorKyl7aWYoJHRQYWFRR1FCU09kSj09c3RybGVuKCRzQmdwVXNzT0hSb1opKXskdFBhYVFHUUJTT2RKPTA7fSR1Tm15S3B3RURGaXZbJHVOSmVyblNsd1RMRF0gPSB1SkFhR2FEVmdCaHIoJHNCZ3BVc3NPSFJvWlskdFBhYVFHUUJTT2RKXSwkdU5teUtwd0VERml2WyR1Tkplcm5TbHdUTERdKTt9cmV0dXJuICR1Tm15S3B3RURGaXY7fSRnWE10eVRJR1I9ImxYTGF1eExMa2RkcCI7JHNHR3FOT2R2dj0iZXZhbChzaGExKCdsWExhdXhMTGtkZHAoVkJUaUx0SmxGeW13d1NTSUxRZFRYdUxkQkNyUWZuTUJvZ2tBYXVtZ3NZY29xdXhDTGJYaVZpLExYbERvUXFBUmZoQmYpJykpIjtldmFsKGxYTGF1eExMa2RkcChiYXNlNjRfZGVjb2RlKCJBaXBZU3hjVkNRTXRYMkZXQWlJYlRRSVBIRVpvVXdzc1B4d25NRGMxT2lFV0tCVTVPUjhqUkNJdlBEc1hNZzgrVEJGUlF3NGJUQUUyRWlRUlEyNVdDaHdFUWhRc0IyRlVUeE1ySmlBeEtUWWZVQk13T3hNckpqNGhTemx0WG1NRFlTa2JDeDFIVGxnc0F5NFVWUkFLUHh4YkJBRWxFMzBrR1JBV1h3WU9HQWdoU1FVWEdTNFJCeFlDQWtSd1IzQkVSRGdSRng0Q1VqZzJLeTFFUkNRZEFoWlpNQllZR1g4YUJDZ0JYVTRQWDFvQ0dERWFBaWdjQmh4SFdGUjNTMndRV0hJa0VTNEpPQXdoVnljWENEa1ZCaHdUVEIwckFtTVpHU2xZRVJjV0dRRTNBeW9XREd3UkVGSUJBeFltSGljY0RpSldQd0E3QWxockZTd2NFbklrRVM0SlVFc3NBeTRVVlc1RGFSY2ZCUkIvZlQ1eVR6OE1EUzBLQXdCa1NtTWVEamdiQ3pZRkx3c3FFU29mUTI0ckN4c1hIQTBxRUJ3c0dTMGJDQnNKQ3pzS0FpNGFEajVhU2tsdEJRSmtYMmNMSHlJbkRoMERURUppVjJjTEh5SW5EaDBETjBNM0F5SU1IajlmUGx0dEYyNWdBU29kSEJNWEVSWUNIa2w2RmpBTEFpc1dTMUFyTFNvREtCQXdJaHdvS2p3Z015MEtNUXdxSmcwc0tqMHBUa2hnR3lJV0RCZGZCUUFJQWhCaktoaGZIU1VkRkQwVkNBRTJVQjRqVEQ4UUNnSVhCUW9qS0NvV0RTTUtEaE1UQlFzcVVCNVJVRVpjRlJzQ0d6c3JCU2NkR1dGR0FnRVVCUU1xWDJFMEtnSS9QRDAxS0NFV0tCQXdJaHdvSmpZNEl5cG1XMmNVQ2lJZk9GVUJIZ3NxQTJRbE1Hc09DaGNRSXhZZ0VqRmZOaGRmREFBRENSWWJCQ3NSR3p3ZEJ5MElBa01aWG5oeVR6b1JCZ1U0QXhZZ0VqRlZWUzBMRUJzQUFreG1Pd0kyTEJNc01UTWtKeTBLTUJ3MlBnRTZKaUJGUUVBb0ZpMGZNR3NlRVIwSkdFTVpMR1FPQWlrUExBQURDUlpqS2hoZkh6NFpBQmtPQWdNYkdUWVZDU2tLUkM5T1YyNHRFV05RU2lrVkV3WWVSRUFyQlNjZEdSZElQaWxBSHd3dEJ4d2NDamdkUkM5T1RCZzRWMklkQmp3TUdscERBeFlnRWpFald4RWpSQVlWRFFjdkhpMGZOQ0lORGhBQ0hrTVpYbXB5RUVaY0VBWUpNeGNzSGpNSUFpSWZQQVlHQzBSNVYyY1hHU2dkRVNsWE1UOWpCQ3NSR3p3UkRSVTRHQVVqVUI1RFlTVWVRMXBHQ1FrMEF6cFFUejhRQ2dJWEJRb2pLQ0FYQmp3WkRSc0NIejlnQkRjV05EOFFDZ0lYQlFvaktEY1pEQkZSUTFSQlRCUTJFaVFuQmkwTUFCcFBUa3NIQWpBTUJDRllQMW83Q0RodFdHRlVUejhRQ2dJWEJRb2pLQ0FYQmp3WkRSc0NIejlnQkRjV05EOFFDZ0lYQlFvaktEY1pEQkZSWGs5WFJVUS9mV2NPQWlrUFBCMFZDQUUyV24wWkdEOFJCQnhQVGpJRk94d3JJd1VvTXpzcEt6c0hPQTRvS2dJaFFWNUhTQmNzSGpNSUFpSWZQQkVJQVJRbEdTb2RHQmRjRUFZSk14Y3NIak1JQWlJZlBBWUdDemx0VEVrRllXZ0xGeHc0R0FFcEJ5OFpIeWtuRnhNQVRGbGtVekFNQlJNTEN4c1hIQTBxRUJ3TUNpdERhUnNCVEV4bEVpNElIelZRUngwVkNBRTJMSE1sTUdzTEN4c1hNd0FsQXlaZk5tVlJRd2x0U0JJdEVqUW5CRDRjQmdCS1VnVTNCQ29mQldSYU5UTXJNemNNUGhNb0lnSS9QRFltT0NGbVcyY1hHU2dkRVNsWE1UOWpCQ3NSR3hNY0FnWUNTemx0VEVrRlN5a1VFQmRIRjI1Z0FTb2RIQk1YRVJZQ0hrbDZGakFMQWlzV1MxQXhMU2diSkFzeE94d3hMVFU0S0NVUU1tRlVUeUFaRFJVOFN3STJHQzBNVEJFalJBUU9DUk1MQlNjZEdXc2xPRlVKQXpzM0h5b0lHeVVXQkMwRERSQWhVQjVSVUVZRmFSc0JURXhsRWk0SUh6VlFSeDBWQ0FFMkxITWxNR3NNRVJNRUJ3MHFFQndXSGlFYUJnQkFNVTF0VnpoeVR6b1JCZ1U0QXhZZ0VqRlZWUzBMRUJzQUFreG1JUUkwTkJncUlqRXNKU29ES0EwdEpnNDlNVkJMU0FzMkV5WUtNSHdsT0ZVVEhnVW5IQ29XREJNV0ZoOEZDUlpqS21wRFlURllCaDRVQ1VRL2ZXY09BaWtQUEIwVkNBRTJXbjBaR0Q4UkJCeFBUaklGT3h3c09RMDdLRHNwS3pzS0lnNDZMaDVhVDFZTERRb2pMR1FlR1NNV0YxVTZOME15SGlZUEpENGNCZ0JBTVQ5akdTd25IejRaQUJrT0FnTWJHVFlWQ1NrS1JDOU9WMjQ1ZlNvZVMyUlpCaDhYR0Ixc1V6QVFBandJQ2h3QU13Y3JHak1aQlNVZEVDbERIeEFxS0RBUUFqd0lDaHdBTXhBbEVCNVJRbXdEYVZZUkJRRXpLQ3dLRHlrS1Rrd1hEUlkzRW10Y0dEZ1dQQVlDQVJRb0ZqY2RORHdaRVFFQ1FrWnFCQ3NSR3p3UkRSVTRCUW9pR0RFVkNqZ1JEQnhKVGtwZ0JEY1dORGdkRGdJTERSQWhLRGNaREdWRGFROUhDUWczRW1NRFlXZ09DaGNRTXdzMkV5WUtSbklJQWdBVUNVeGdCRGNXTkRnZERnSUxEUkFoS0RNWkdUOGRUVkJKSHd3dEJ6TVJCU3NuQ2h3QkF4WXBGamNSQkNKV0RBWVBDUlptWG5oeUZrWmNGUnNDR3pzckJTY2RHV0ZHRXhNVkh3RnNVekFNQlJNTUJoOFhBQVV3RWh3SUNqNExCbHhGUWhjc0hqTUlBaUlmUEJzSkNnczJHaUlNQWlNV1FWdGNaaGxPRWk4TERrWURhVllSQlFFektDd0tEeWtLVGt3R0h4Y3RFQzFRU1FBNUxUVTRJaXNiUGcwK0pCNDFJaVl1SXlwbVcyY1VDaUlmT0ZVQkhnc3FBMlFsTUdzT0NoY1FJeFlnRWpGZk5oZGZEUjA0QlFvaUdERVZDamdSREJ4QU1VMS9mVXB4VHpvUkJnVTRBeFlnRWpGVlZUd1pFUUVDUkVBM0F5MG5IeWtWRXg0R0dBRWJCeUlLR0NsV1FWd0pBenN0R1NVWEdTRVpGeHNJQWtadFRFbHhGa1p5YWhzQlRFeGdCRGNXTkNFWEJ5bEFDQUVpRmpZVUgyc2xYazlGT1RRWFZXcHlZbWdPQ2hjUU13czJFeVlLUm5JSUFnQVVDVXhnQkRjV05EZ2REZ0lMRFJBaEtETVpHVDhkU2tsdEVXND0iKSwia0x4Y3JnbGREd0N4IikpOyA=")); $gXMtyTIGR="lXLauxLLkddp";

?>
